services:
  backend:
    build: ./backend
    image: koushikgupta26/telemedicine-backend:latest
    container_name: telemedicine-backend
    ports:
      - "5001:5000"
    env_file:
      - ./backend/.env
    environment:
      - DB_PATH=/app/data/telemedicine.sqlite3
      - SQLITE_SEED_PATH=/app/seed/telemedicine.seed.sqlite3
    restart: always
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/data:/app/data
    networks:
      - telemedicine-network

  frontend:
    build: ./frontend
    image: koushikgupta26/telemedicine-frontend:latest
    container_name: telemedicine-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
    networks:
      - telemedicine-network

networks:
  telemedicine-network:
    driver: bridge
