const doctorDashboardCopy = {
  en: {
    nav: {
      doctorSpace: "Doctor space",
      practice: "Practice",
      personal: "Personal",
      schedule: "Schedule",
      patients: "Patients",
      prescriptions: "Prescriptions",
      availability: "Availability",
      analytics: "Analytics",
      profile: "Profile",
      logout: "Logout",
    },
    topbar: {
      eyebrow: "Doctor dashboard",
      titlePrefix: "Care hub for Dr.",
      searchPatients: "Search patients...",
      practiceSynced: "Practice synced",
      online: "Online",
      switchLight: "Switch to light mode",
      switchDark: "Switch to dark mode",
      doctorAlt: "Doctor",
    },
    schedule: {
      loading: "Loading schedule...",
      fetchFailedDefault: "Failed to fetch schedule.",
      failedTitle: "Failed to load schedule",
      retry: "Retry",
      heroEyebrow: "Practice command center",
      title: "Today's Schedule",
      description: "Manage consultations, patient flow, prescriptions, and availability from one calm clinical workspace.",
      quickActions: "Quick actions",
      clinicalTools: "Clinical tools",
      stats: {
        todayAppointments: "Today's Appointments",
        consultationsScheduled: "Consultations scheduled",
        upcomingThisWeek: "Upcoming This Week",
        nextSevenDays: "Next 7 days",
        patientsConsulted: "Patients Consulted",
        completedVisits: "Completed visits",
        revenue: "Revenue",
        estimatedFromCompleted: "Estimated from completed",
        onlineStatus: "Online Status",
        live: "Live",
        readyForCalls: "Ready for calls",
      },
      actions: {
        startInstantConsultation: "Start Instant Consultation",
        addPrescription: "Add Prescription",
        viewPatients: "View Patients",
        availabilitySettings: "Availability Settings",
        analytics: "Analytics",
      },
      premiumQueue: "Premium consultation queue with status and call controls.",
      upcoming: "Upcoming",
      noAppointmentsTitle: "No appointments today",
      noAppointmentsText: "You do not have any consultations scheduled right now.",
      timeline: "Timeline",
      upcomingReminders: "Upcoming reminders",
      patientConsultation: "Patient consultation",
      patient: "Patient",
      urgent: "Urgent",
      routine: "Routine",
      scheduled: "Scheduled",
      video: "Video",
      viewDetails: "View Details",
      startCall: "Start Call",
    },
    patients: {
      loadingDetails: "Loading patient details...",
      detailsNotFound: "Patient details not found.",
      backToList: "Back to list",
      backToPatients: "Back to Patients",
      profile: "Patient profile",
      dob: "DOB",
      history: "Consultation History",
      doctorNotes: "Doctor's Notes",
      prescribedMedicines: "Prescribed Medicines",
      noHistory: "No previous consultation history found with this doctor.",
      startNewConsultation: "Start New Consultation",
      directory: "Patient directory",
      recentPatients: "Recent Patients",
      description: "Search and review your recent patient interactions.",
      searchPlaceholder: "Search patients, tags...",
      noRecent: "No recent patients found.",
      active: "Active",
      recent: "Recent",
      generalConsult: "General consult",
      ageGenderPending: "Age/Gender pending",
      lastVisit: "Last visit",
      recently: "Recently",
    },
    prescriptions: {
      detailsNotFound: "Prescription details not found.",
      backToList: "Back to list",
      backToPrescriptions: "Back to Prescriptions",
      prescription: "Prescription",
      issuedOn: "Issued on",
      copy: "Copy",
      medications: "Medications",
      instructions: "Instructions",
      manager: "Prescription manager",
      issuedPrescriptions: "Issued Prescriptions",
      description: "Search, review, and export prescription history.",
      generateNew: "Generate New",
      searchPlaceholder: "Search patient, medicine, notes...",
      noPrescriptions: "No prescriptions found.",
      date: "Date",
    },
    availability: {
      fetchFailed: "Failed to fetch schedule",
      saved: "Schedule saved successfully!",
      saveFailed: "Failed to save schedule.",
      networkError: "Network error occurred.",
      planner: "Availability planner",
      weeklySchedule: "Weekly Schedule",
      description: "Set recurring slots, break times, and online readiness.",
      saveChanges: "Save Changes",
      activeDays: "Active days",
      defaultStart: "Default start",
      breakBuffer: "Break buffer",
      availableForConsultations: "Available for consultations",
      unavailable: "Unavailable",
      to: "to",
      videoChat: "Video + Chat",
      breaksAutoBuffered: "Breaks auto-buffered",
      noBookings: "No patient bookings for this day.",
      days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
    },
    analytics: {
      loading: "Loading analytics...",
      failed: "Failed to load analytics.",
      intelligence: "Practice intelligence",
      title: "Analytics",
      description: "Track consultations completed, response momentum, growth, and patient mix.",
      weeklyTrend: "+12% weekly trend",
      totalPatients: "Total Patients",
      lifetimeReach: "Lifetime reach",
      completed: "Completed",
      thisMonth: "This month",
      revenue: "Revenue",
      estimatedEarnings: "Estimated earnings",
      satisfaction: "Satisfaction",
      patientRating: "Patient rating",
      consultationGrowth: "Consultation Growth",
      weeklyAppointmentTrend: "Weekly appointment trend",
      patientMix: "Patient Mix",
      demographicDistribution: "Demographic distribution",
      noData: "No data available",
      patients: "Patients",
    },
    profile: {
      updatePictureTitle: "Update profile picture",
      uploadingPhoto: "Uploading photo...",
      professionalProfile: "Professional profile",
      description: "Keep your public profile polished for patients reviewing your care details.",
      commandCenter: "Profile command center",
      title: "Professional Profile",
      summary: "Manage specialization, clinic identity, certifications, consultation fee, and availability summary.",
      updateFailed: "Failed to update profile.",
      updated: "Profile updated successfully!",
      pictureUpdateFailed: "Failed to update profile picture.",
      pictureUpdated: "Profile picture updated successfully!",
      errorPrefix: "Error:",
      stats: {
        specialization: "Specialization",
        addSpecialty: "Add specialty",
        experience: "Experience",
        addYears: "Add years",
        fee: "Fee",
        addFee: "Add fee",
      },
      sections: {
        basicInformation: "Basic Information",
        clinicDetails: "Clinic Details",
        professionalBio: "Professional Bio",
      },
      fields: {
        specialty: "Specialty",
        specialtyPlaceholder: "e.g. Cardiologist",
        qualification: "Qualification",
        qualificationPlaceholder: "e.g. MBBS, MD",
        experience: "Experience",
        experiencePlaceholder: "e.g. 10 Years",
        fee: "Consultation Fee",
        feePlaceholder: "e.g. 500",
        languages: "Languages Spoken",
        languagesPlaceholder: "e.g. English, Hindi",
        clinicName: "Clinic Name",
        clinicNamePlaceholder: "Your Clinic Name",
        registrationNumber: "Registration Number",
        registrationPlaceholder: "Medical Council Reg. No",
        clinicAddress: "Clinic Address",
        clinicAddressPlaceholder: "Full address of your clinic...",
        bioPlaceholder: "Tell patients about your experience and medical philosophy...",
      },
      saving: "Saving Changes...",
      saveProfile: "Save Profile",
    },
  },
  hi: {
    nav: {
      doctorSpace: "डॉक्टर स्पेस",
      practice: "प्रैक्टिस",
      personal: "व्यक्तिगत",
      schedule: "शेड्यूल",
      patients: "मरीज़",
      prescriptions: "प्रिस्क्रिप्शन",
      availability: "उपलब्धता",
      analytics: "एनालिटिक्स",
      profile: "प्रोफ़ाइल",
      logout: "लॉग आउट",
    },
    topbar: {
      eyebrow: "डॉक्टर डैशबोर्ड",
      titlePrefix: "डॉ. के लिए केयर हब",
      searchPatients: "मरीज़ खोजें...",
      practiceSynced: "प्रैक्टिस सिंक है",
      online: "ऑनलाइन",
      switchLight: "लाइट मोड पर जाएं",
      switchDark: "डार्क मोड पर जाएं",
      doctorAlt: "डॉक्टर",
    },
    schedule: {
      loading: "शेड्यूल लोड हो रहा है...",
      fetchFailedDefault: "शेड्यूल लाने में विफल.",
      failedTitle: "शेड्यूल लोड नहीं हो सका",
      retry: "फिर कोशिश करें",
      heroEyebrow: "प्रैक्टिस कमांड सेंटर",
      title: "आज का शेड्यूल",
      description: "कंसल्टेशन, मरीजों की कतार, प्रिस्क्रिप्शन और उपलब्धता एक शांत क्लिनिकल वर्कस्पेस से संभालें.",
      quickActions: "त्वरित कार्य",
      clinicalTools: "क्लिनिकल टूल्स",
      stats: {
        todayAppointments: "आज की अपॉइंटमेंट",
        consultationsScheduled: "कंसल्टेशन निर्धारित",
        upcomingThisWeek: "इस सप्ताह आगामी",
        nextSevenDays: "अगले 7 दिन",
        patientsConsulted: "देखे गए मरीज़",
        completedVisits: "पूर्ण विज़िट",
        revenue: "आय",
        estimatedFromCompleted: "पूर्ण विज़िट से अनुमान",
        onlineStatus: "ऑनलाइन स्थिति",
        live: "लाइव",
        readyForCalls: "कॉल के लिए तैयार",
      },
      actions: {
        startInstantConsultation: "तुरंत कंसल्टेशन शुरू करें",
        addPrescription: "प्रिस्क्रिप्शन जोड़ें",
        viewPatients: "मरीज़ देखें",
        availabilitySettings: "उपलब्धता सेटिंग्स",
        analytics: "एनालिटिक्स",
      },
      premiumQueue: "स्टेटस और कॉल नियंत्रणों के साथ प्रीमियम कंसल्टेशन कतार.",
      upcoming: "आगामी",
      noAppointmentsTitle: "आज कोई अपॉइंटमेंट नहीं",
      noAppointmentsText: "अभी आपके लिए कोई कंसल्टेशन निर्धारित नहीं है.",
      timeline: "टाइमलाइन",
      upcomingReminders: "आगामी रिमाइंडर",
      patientConsultation: "मरीज़ कंसल्टेशन",
      patient: "मरीज़",
      urgent: "तत्काल",
      routine: "नियमित",
      scheduled: "निर्धारित",
      video: "वीडियो",
      viewDetails: "विवरण देखें",
      startCall: "कॉल शुरू करें",
    },
    patients: {
      loadingDetails: "मरीज़ विवरण लोड हो रहा है...",
      detailsNotFound: "मरीज़ विवरण नहीं मिला.",
      backToList: "सूची पर वापस",
      backToPatients: "मरीज़ों पर वापस",
      profile: "मरीज़ प्रोफ़ाइल",
      dob: "जन्म तिथि",
      history: "कंसल्टेशन इतिहास",
      doctorNotes: "डॉक्टर के नोट्स",
      prescribedMedicines: "लिखी गई दवाएं",
      noHistory: "इस डॉक्टर के साथ पिछला कंसल्टेशन इतिहास नहीं मिला.",
      startNewConsultation: "नया कंसल्टेशन शुरू करें",
      directory: "मरीज़ डायरेक्टरी",
      recentPatients: "हाल के मरीज़",
      description: "हाल की मरीज़ इंटरैक्शन खोजें और समीक्षा करें.",
      searchPlaceholder: "मरीज़, टैग खोजें...",
      noRecent: "कोई हाल का मरीज़ नहीं मिला.",
      active: "सक्रिय",
      recent: "हाल का",
      generalConsult: "सामान्य कंसल्ट",
      ageGenderPending: "उम्र/लिंग बाकी",
      lastVisit: "अंतिम विज़िट",
      recently: "हाल ही में",
    },
    prescriptions: {
      detailsNotFound: "प्रिस्क्रिप्शन विवरण नहीं मिला.",
      backToList: "सूची पर वापस",
      backToPrescriptions: "प्रिस्क्रिप्शन पर वापस",
      prescription: "प्रिस्क्रिप्शन",
      issuedOn: "जारी किया गया",
      copy: "कॉपी",
      medications: "दवाएं",
      instructions: "निर्देश",
      manager: "प्रिस्क्रिप्शन मैनेजर",
      issuedPrescriptions: "जारी प्रिस्क्रिप्शन",
      description: "प्रिस्क्रिप्शन इतिहास खोजें, समीक्षा करें और निर्यात करें.",
      generateNew: "नया बनाएं",
      searchPlaceholder: "मरीज़, दवा, नोट्स खोजें...",
      noPrescriptions: "कोई प्रिस्क्रिप्शन नहीं मिला.",
      date: "तारीख",
    },
    availability: {
      fetchFailed: "शेड्यूल लाने में विफल",
      saved: "शेड्यूल सफलतापूर्वक सेव हुआ!",
      saveFailed: "शेड्यूल सेव नहीं हो सका.",
      networkError: "नेटवर्क त्रुटि हुई.",
      planner: "उपलब्धता प्लानर",
      weeklySchedule: "साप्ताहिक शेड्यूल",
      description: "दोहराए जाने वाले स्लॉट, ब्रेक समय और ऑनलाइन तैयारी सेट करें.",
      saveChanges: "बदलाव सेव करें",
      activeDays: "सक्रिय दिन",
      defaultStart: "डिफ़ॉल्ट शुरू",
      breakBuffer: "ब्रेक बफ़र",
      availableForConsultations: "कंसल्टेशन के लिए उपलब्ध",
      unavailable: "उपलब्ध नहीं",
      to: "से",
      videoChat: "वीडियो + चैट",
      breaksAutoBuffered: "ब्रेक अपने आप बफ़र",
      noBookings: "इस दिन मरीज बुकिंग नहीं है.",
      days: ["सोमवार", "मंगलवार", "बुधवार", "गुरुवार", "शुक्रवार", "शनिवार", "रविवार"],
    },
    analytics: {
      loading: "एनालिटिक्स लोड हो रहा है...",
      failed: "एनालिटिक्स लोड नहीं हो सका.",
      intelligence: "प्रैक्टिस इंटेलिजेंस",
      title: "एनालिटिक्स",
      description: "पूर्ण कंसल्टेशन, गति, वृद्धि और मरीज़ मिश्रण ट्रैक करें.",
      weeklyTrend: "+12% साप्ताहिक रुझान",
      totalPatients: "कुल मरीज़",
      lifetimeReach: "कुल पहुंच",
      completed: "पूर्ण",
      thisMonth: "इस महीने",
      revenue: "आय",
      estimatedEarnings: "अनुमानित कमाई",
      satisfaction: "संतुष्टि",
      patientRating: "मरीज़ रेटिंग",
      consultationGrowth: "कंसल्टेशन वृद्धि",
      weeklyAppointmentTrend: "साप्ताहिक अपॉइंटमेंट रुझान",
      patientMix: "मरीज़ मिश्रण",
      demographicDistribution: "जनसांख्यिकीय वितरण",
      noData: "डेटा उपलब्ध नहीं",
      patients: "मरीज़",
    },
    profile: {
      updatePictureTitle: "प्रोफ़ाइल फोटो अपडेट करें",
      uploadingPhoto: "फोटो अपलोड हो रही है...",
      professionalProfile: "प्रोफ़ेशनल प्रोफ़ाइल",
      description: "मरीज़ों के लिए अपनी सार्वजनिक प्रोफ़ाइल साफ और भरोसेमंद रखें.",
      commandCenter: "प्रोफ़ाइल कमांड सेंटर",
      title: "प्रोफ़ेशनल प्रोफ़ाइल",
      summary: "विशेषज्ञता, क्लिनिक पहचान, प्रमाणपत्र, फीस और उपलब्धता सारांश संभालें.",
      updateFailed: "प्रोफ़ाइल अपडेट नहीं हो सकी.",
      updated: "प्रोफ़ाइल सफलतापूर्वक अपडेट हुई!",
      pictureUpdateFailed: "प्रोफ़ाइल फोटो अपडेट नहीं हो सकी.",
      pictureUpdated: "प्रोफ़ाइल फोटो सफलतापूर्वक अपडेट हुई!",
      errorPrefix: "त्रुटि:",
      stats: {
        specialization: "विशेषज्ञता",
        addSpecialty: "विशेषज्ञता जोड़ें",
        experience: "अनुभव",
        addYears: "वर्ष जोड़ें",
        fee: "फीस",
        addFee: "फीस जोड़ें",
      },
      sections: {
        basicInformation: "मूल जानकारी",
        clinicDetails: "क्लिनिक विवरण",
        professionalBio: "प्रोफ़ेशनल बायो",
      },
      fields: {
        specialty: "विशेषता",
        specialtyPlaceholder: "जैसे कार्डियोलॉजिस्ट",
        qualification: "योग्यता",
        qualificationPlaceholder: "जैसे MBBS, MD",
        experience: "अनुभव",
        experiencePlaceholder: "जैसे 10 वर्ष",
        fee: "कंसल्टेशन फीस",
        feePlaceholder: "जैसे 500",
        languages: "बोली जाने वाली भाषाएं",
        languagesPlaceholder: "जैसे अंग्रेज़ी, हिंदी",
        clinicName: "क्लिनिक नाम",
        clinicNamePlaceholder: "आपके क्लिनिक का नाम",
        registrationNumber: "रजिस्ट्रेशन नंबर",
        registrationPlaceholder: "मेडिकल काउंसिल रजि. नंबर",
        clinicAddress: "क्लिनिक पता",
        clinicAddressPlaceholder: "आपके क्लिनिक का पूरा पता...",
        bioPlaceholder: "मरीज़ों को अपने अनुभव और चिकित्सा सोच के बारे में बताएं...",
      },
      saving: "बदलाव सेव हो रहे हैं...",
      saveProfile: "प्रोफ़ाइल सेव करें",
    },
  },
  bn: {
    nav: {
      doctorSpace: "ডাক্তার স্পেস",
      practice: "প্র্যাকটিস",
      personal: "ব্যক্তিগত",
      schedule: "সময়সূচি",
      patients: "রোগী",
      prescriptions: "প্রেসক্রিপশন",
      availability: "উপলভ্যতা",
      analytics: "অ্যানালিটিক্স",
      profile: "প্রোফাইল",
      logout: "লগ আউট",
    },
    topbar: {
      eyebrow: "ডাক্তার ড্যাশবোর্ড",
      titlePrefix: "ডা. এর জন্য কেয়ার হাব",
      searchPatients: "রোগী খুঁজুন...",
      practiceSynced: "প্র্যাকটিস সিঙ্ক হয়েছে",
      online: "অনলাইন",
      switchLight: "লাইট মোডে যান",
      switchDark: "ডার্ক মোডে যান",
      doctorAlt: "ডাক্তার",
    },
    schedule: {
      loading: "সময়সূচি লোড হচ্ছে...",
      fetchFailedDefault: "সময়সূচি আনতে ব্যর্থ.",
      failedTitle: "সময়সূচি লোড হয়নি",
      retry: "আবার চেষ্টা করুন",
      heroEyebrow: "প্র্যাকটিস কমান্ড সেন্টার",
      title: "আজকের সময়সূচি",
      description: "কনসাল্টেশন, রোগীর প্রবাহ, প্রেসক্রিপশন ও উপলভ্যতা এক শান্ত ক্লিনিক্যাল ওয়ার্কস্পেসে পরিচালনা করুন.",
      quickActions: "দ্রুত কাজ",
      clinicalTools: "ক্লিনিক্যাল টুলস",
      stats: {
        todayAppointments: "আজকের অ্যাপয়েন্টমেন্ট",
        consultationsScheduled: "নির্ধারিত কনসাল্টেশন",
        upcomingThisWeek: "এই সপ্তাহের আসন্ন",
        nextSevenDays: "পরের ৭ দিন",
        patientsConsulted: "পরামর্শপ্রাপ্ত রোগী",
        completedVisits: "সম্পন্ন ভিজিট",
        revenue: "আয়",
        estimatedFromCompleted: "সম্পন্ন ভিজিট থেকে অনুমান",
        onlineStatus: "অনলাইন অবস্থা",
        live: "লাইভ",
        readyForCalls: "কলের জন্য প্রস্তুত",
      },
      actions: {
        startInstantConsultation: "তাৎক্ষণিক কনসাল্টেশন শুরু করুন",
        addPrescription: "প্রেসক্রিপশন যোগ করুন",
        viewPatients: "রোগী দেখুন",
        availabilitySettings: "উপলভ্যতা সেটিংস",
        analytics: "অ্যানালিটিক্স",
      },
      premiumQueue: "স্ট্যাটাস ও কল নিয়ন্ত্রণসহ প্রিমিয়াম কনসাল্টেশন সারি.",
      upcoming: "আসন্ন",
      noAppointmentsTitle: "আজ কোনো অ্যাপয়েন্টমেন্ট নেই",
      noAppointmentsText: "এই মুহূর্তে আপনার কোনো কনসাল্টেশন নির্ধারিত নেই.",
      timeline: "টাইমলাইন",
      upcomingReminders: "আসন্ন রিমাইন্ডার",
      patientConsultation: "রোগী কনসাল্টেশন",
      patient: "রোগী",
      urgent: "জরুরি",
      routine: "নিয়মিত",
      scheduled: "নির্ধারিত",
      video: "ভিডিও",
      viewDetails: "বিস্তারিত দেখুন",
      startCall: "কল শুরু করুন",
    },
    patients: {
      loadingDetails: "রোগীর বিস্তারিত লোড হচ্ছে...",
      detailsNotFound: "রোগীর বিস্তারিত পাওয়া যায়নি.",
      backToList: "তালিকায় ফিরুন",
      backToPatients: "রোগীদের কাছে ফিরুন",
      profile: "রোগীর প্রোফাইল",
      dob: "জন্মতারিখ",
      history: "কনসাল্টেশন ইতিহাস",
      doctorNotes: "ডাক্তারের নোট",
      prescribedMedicines: "নির্ধারিত ওষুধ",
      noHistory: "এই ডাক্তারের সঙ্গে আগের কোনো কনসাল্টেশন ইতিহাস পাওয়া যায়নি.",
      startNewConsultation: "নতুন কনসাল্টেশন শুরু করুন",
      directory: "রোগী ডিরেক্টরি",
      recentPatients: "সাম্প্রতিক রোগী",
      description: "সাম্প্রতিক রোগী যোগাযোগ খুঁজুন ও পর্যালোচনা করুন.",
      searchPlaceholder: "রোগী, ট্যাগ খুঁজুন...",
      noRecent: "সাম্প্রতিক কোনো রোগী পাওয়া যায়নি.",
      active: "সক্রিয়",
      recent: "সাম্প্রতিক",
      generalConsult: "সাধারণ কনসাল্ট",
      ageGenderPending: "বয়স/লিঙ্গ বাকি",
      lastVisit: "শেষ ভিজিট",
      recently: "সম্প্রতি",
    },
    prescriptions: {
      detailsNotFound: "প্রেসক্রিপশনের বিস্তারিত পাওয়া যায়নি.",
      backToList: "তালিকায় ফিরুন",
      backToPrescriptions: "প্রেসক্রিপশনে ফিরুন",
      prescription: "প্রেসক্রিপশন",
      issuedOn: "জারি হয়েছে",
      copy: "কপি",
      medications: "ওষুধ",
      instructions: "নির্দেশনা",
      manager: "প্রেসক্রিপশন ম্যানেজার",
      issuedPrescriptions: "জারি করা প্রেসক্রিপশন",
      description: "প্রেসক্রিপশন ইতিহাস খুঁজুন, পর্যালোচনা করুন ও এক্সপোর্ট করুন.",
      generateNew: "নতুন তৈরি করুন",
      searchPlaceholder: "রোগী, ওষুধ, নোট খুঁজুন...",
      noPrescriptions: "কোনো প্রেসক্রিপশন পাওয়া যায়নি.",
      date: "তারিখ",
    },
    availability: {
      fetchFailed: "সময়সূচি আনতে ব্যর্থ",
      saved: "সময়সূচি সফলভাবে সেভ হয়েছে!",
      saveFailed: "সময়সূচি সেভ হয়নি.",
      networkError: "নেটওয়ার্ক ত্রুটি হয়েছে.",
      planner: "উপলভ্যতা প্ল্যানার",
      weeklySchedule: "সাপ্তাহিক সময়সূচি",
      description: "পুনরাবৃত্ত স্লট, বিরতির সময় ও অনলাইন প্রস্তুতি সেট করুন.",
      saveChanges: "পরিবর্তন সেভ করুন",
      activeDays: "সক্রিয় দিন",
      defaultStart: "ডিফল্ট শুরু",
      breakBuffer: "বিরতি বাফার",
      availableForConsultations: "কনসাল্টেশনের জন্য উপলভ্য",
      unavailable: "উপলভ্য নয়",
      to: "থেকে",
      videoChat: "ভিডিও + চ্যাট",
      breaksAutoBuffered: "বিরতি অটো-বাফার্ড",
      noBookings: "এই দিনে কোনো রোগী বুকিং নেই.",
      days: ["সোমবার", "মঙ্গলবার", "বুধবার", "বৃহস্পতিবার", "শুক্রবার", "শনিবার", "রবিবার"],
    },
    analytics: {
      loading: "অ্যানালিটিক্স লোড হচ্ছে...",
      failed: "অ্যানালিটিক্স লোড হয়নি.",
      intelligence: "প্র্যাকটিস ইন্টেলিজেন্স",
      title: "অ্যানালিটিক্স",
      description: "সম্পন্ন কনসাল্টেশন, গতি, বৃদ্ধি ও রোগী মিশ্রণ ট্র্যাক করুন.",
      weeklyTrend: "+12% সাপ্তাহিক ট্রেন্ড",
      totalPatients: "মোট রোগী",
      lifetimeReach: "সর্বমোট পৌঁছ",
      completed: "সম্পন্ন",
      thisMonth: "এই মাস",
      revenue: "আয়",
      estimatedEarnings: "আনুমানিক আয়",
      satisfaction: "সন্তুষ্টি",
      patientRating: "রোগী রেটিং",
      consultationGrowth: "কনসাল্টেশন বৃদ্ধি",
      weeklyAppointmentTrend: "সাপ্তাহিক অ্যাপয়েন্টমেন্ট ট্রেন্ড",
      patientMix: "রোগী মিশ্রণ",
      demographicDistribution: "জনতাত্ত্বিক বিতরণ",
      noData: "ডেটা নেই",
      patients: "রোগী",
    },
    profile: {
      updatePictureTitle: "প্রোফাইল ছবি আপডেট করুন",
      uploadingPhoto: "ছবি আপলোড হচ্ছে...",
      professionalProfile: "পেশাগত প্রোফাইল",
      description: "রোগীরা যেন আপনার পরিচর্যার তথ্য আত্মবিশ্বাসের সঙ্গে দেখে, তাই পাবলিক প্রোফাইল গুছিয়ে রাখুন.",
      commandCenter: "প্রোফাইল কমান্ড সেন্টার",
      title: "পেশাগত প্রোফাইল",
      summary: "বিশেষত্ব, ক্লিনিক পরিচয়, সার্টিফিকেশন, ফি ও উপলভ্যতার সারাংশ পরিচালনা করুন.",
      updateFailed: "প্রোফাইল আপডেট হয়নি.",
      updated: "প্রোফাইল সফলভাবে আপডেট হয়েছে!",
      pictureUpdateFailed: "প্রোফাইল ছবি আপডেট হয়নি.",
      pictureUpdated: "প্রোফাইল ছবি সফলভাবে আপডেট হয়েছে!",
      errorPrefix: "ত্রুটি:",
      stats: {
        specialization: "বিশেষায়ন",
        addSpecialty: "বিশেষত্ব যোগ করুন",
        experience: "অভিজ্ঞতা",
        addYears: "বছর যোগ করুন",
        fee: "ফি",
        addFee: "ফি যোগ করুন",
      },
      sections: {
        basicInformation: "মৌলিক তথ্য",
        clinicDetails: "ক্লিনিকের বিস্তারিত",
        professionalBio: "পেশাগত বায়ো",
      },
      fields: {
        specialty: "বিশেষত্ব",
        specialtyPlaceholder: "যেমন কার্ডিওলজিস্ট",
        qualification: "যোগ্যতা",
        qualificationPlaceholder: "যেমন MBBS, MD",
        experience: "অভিজ্ঞতা",
        experiencePlaceholder: "যেমন ১০ বছর",
        fee: "কনসাল্টেশন ফি",
        feePlaceholder: "যেমন 500",
        languages: "বলা ভাষা",
        languagesPlaceholder: "যেমন English, Hindi",
        clinicName: "ক্লিনিকের নাম",
        clinicNamePlaceholder: "আপনার ক্লিনিকের নাম",
        registrationNumber: "রেজিস্ট্রেশন নম্বর",
        registrationPlaceholder: "মেডিক্যাল কাউন্সিল রেজি. নং",
        clinicAddress: "ক্লিনিকের ঠিকানা",
        clinicAddressPlaceholder: "আপনার ক্লিনিকের পূর্ণ ঠিকানা...",
        bioPlaceholder: "রোগীদের আপনার অভিজ্ঞতা ও চিকিৎসা ভাবনা সম্পর্কে বলুন...",
      },
      saving: "পরিবর্তন সেভ হচ্ছে...",
      saveProfile: "প্রোফাইল সেভ করুন",
    },
  },
  pa: {
    nav: {
      doctorSpace: "ਡਾਕਟਰ ਸਪੇਸ",
      practice: "ਪ੍ਰੈਕਟਿਸ",
      personal: "ਨਿੱਜੀ",
      schedule: "ਸ਼ਡਿਊਲ",
      patients: "ਮਰੀਜ਼",
      prescriptions: "ਪ੍ਰਿਸਕ੍ਰਿਪਸ਼ਨ",
      availability: "ਉਪਲਬਧਤਾ",
      analytics: "ਐਨਾਲਿਟਿਕਸ",
      profile: "ਪ੍ਰੋਫਾਈਲ",
      logout: "ਲਾਗ ਆਉਟ",
    },
    topbar: {
      eyebrow: "ਡਾਕਟਰ ਡੈਸ਼ਬੋਰਡ",
      titlePrefix: "ਡਾ. ਲਈ ਕੇਅਰ ਹੱਬ",
      searchPatients: "ਮਰੀਜ਼ ਲੱਭੋ...",
      practiceSynced: "ਪ੍ਰੈਕਟਿਸ ਸਿੰਕ ਹੈ",
      online: "ਆਨਲਾਈਨ",
      switchLight: "ਲਾਈਟ ਮੋਡ ਤੇ ਜਾਓ",
      switchDark: "ਡਾਰਕ ਮੋਡ ਤੇ ਜਾਓ",
      doctorAlt: "ਡਾਕਟਰ",
    },
    schedule: {
      loading: "ਸ਼ਡਿਊਲ ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...",
      fetchFailedDefault: "ਸ਼ਡਿਊਲ ਲਿਆਉਣ ਵਿੱਚ ਅਸਫਲ.",
      failedTitle: "ਸ਼ਡਿਊਲ ਲੋਡ ਨਹੀਂ ਹੋਇਆ",
      retry: "ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ",
      heroEyebrow: "ਪ੍ਰੈਕਟਿਸ ਕਮਾਂਡ ਸੈਂਟਰ",
      title: "ਅੱਜ ਦਾ ਸ਼ਡਿਊਲ",
      description: "ਕਨਸਲਟੇਸ਼ਨ, ਮਰੀਜ਼ ਫਲੋ, ਪ੍ਰਿਸਕ੍ਰਿਪਸ਼ਨ ਅਤੇ ਉਪਲਬਧਤਾ ਇੱਕ ਸ਼ਾਂਤ ਕਲੀਨਿਕਲ ਵਰਕਸਪੇਸ ਤੋਂ ਸੰਭਾਲੋ.",
      quickActions: "ਤੁਰੰਤ ਕਾਰਵਾਈਆਂ",
      clinicalTools: "ਕਲੀਨਿਕਲ ਟੂਲ",
      stats: {
        todayAppointments: "ਅੱਜ ਦੀਆਂ ਅਪਾਇੰਟਮੈਂਟਾਂ",
        consultationsScheduled: "ਕਨਸਲਟੇਸ਼ਨ ਤੈਅ",
        upcomingThisWeek: "ਇਸ ਹਫ਼ਤੇ ਆਉਣ ਵਾਲੀਆਂ",
        nextSevenDays: "ਅਗਲੇ 7 ਦਿਨ",
        patientsConsulted: "ਦੇਖੇ ਮਰੀਜ਼",
        completedVisits: "ਪੂਰੀਆਂ ਵਿਜ਼ਿਟਾਂ",
        revenue: "ਆਮਦਨ",
        estimatedFromCompleted: "ਪੂਰੀਆਂ ਤੋਂ ਅਨੁਮਾਨ",
        onlineStatus: "ਆਨਲਾਈਨ ਸਥਿਤੀ",
        live: "ਲਾਈਵ",
        readyForCalls: "ਕਾਲਾਂ ਲਈ ਤਿਆਰ",
      },
      actions: {
        startInstantConsultation: "ਤੁਰੰਤ ਕਨਸਲਟੇਸ਼ਨ ਸ਼ੁਰੂ ਕਰੋ",
        addPrescription: "ਪ੍ਰਿਸਕ੍ਰਿਪਸ਼ਨ ਜੋੜੋ",
        viewPatients: "ਮਰੀਜ਼ ਵੇਖੋ",
        availabilitySettings: "ਉਪਲਬਧਤਾ ਸੈਟਿੰਗਾਂ",
        analytics: "ਐਨਾਲਿਟਿਕਸ",
      },
      premiumQueue: "ਸਟੇਟਸ ਅਤੇ ਕਾਲ ਕੰਟਰੋਲਾਂ ਨਾਲ ਪ੍ਰੀਮੀਅਮ ਕਨਸਲਟੇਸ਼ਨ ਕਤਾਰ.",
      upcoming: "ਆਉਣ ਵਾਲੀਆਂ",
      noAppointmentsTitle: "ਅੱਜ ਕੋਈ ਅਪਾਇੰਟਮੈਂਟ ਨਹੀਂ",
      noAppointmentsText: "ਇਸ ਵੇਲੇ ਤੁਹਾਡੇ ਲਈ ਕੋਈ ਕਨਸਲਟੇਸ਼ਨ ਤੈਅ ਨਹੀਂ.",
      timeline: "ਟਾਈਮਲਾਈਨ",
      upcomingReminders: "ਆਉਣ ਵਾਲੇ ਰਿਮਾਈਂਡਰ",
      patientConsultation: "ਮਰੀਜ਼ ਕਨਸਲਟੇਸ਼ਨ",
      patient: "ਮਰੀਜ਼",
      urgent: "ਤੁਰੰਤ",
      routine: "ਰੁਟੀਨ",
      scheduled: "ਤੈਅ",
      video: "ਵੀਡੀਓ",
      viewDetails: "ਵੇਰਵੇ ਵੇਖੋ",
      startCall: "ਕਾਲ ਸ਼ੁਰੂ ਕਰੋ",
    },
    patients: {
      loadingDetails: "ਮਰੀਜ਼ ਵੇਰਵੇ ਲੋਡ ਹੋ ਰਹੇ ਹਨ...",
      detailsNotFound: "ਮਰੀਜ਼ ਵੇਰਵੇ ਨਹੀਂ ਮਿਲੇ.",
      backToList: "ਸੂਚੀ ਵੱਲ ਵਾਪਸ",
      backToPatients: "ਮਰੀਜ਼ਾਂ ਵੱਲ ਵਾਪਸ",
      profile: "ਮਰੀਜ਼ ਪ੍ਰੋਫਾਈਲ",
      dob: "ਜਨਮ ਮਿਤੀ",
      history: "ਕਨਸਲਟੇਸ਼ਨ ਇਤਿਹਾਸ",
      doctorNotes: "ਡਾਕਟਰ ਦੇ ਨੋਟ",
      prescribedMedicines: "ਲਿਖੀਆਂ ਦਵਾਈਆਂ",
      noHistory: "ਇਸ ਡਾਕਟਰ ਨਾਲ ਪਿਛਲਾ ਕਨਸਲਟੇਸ਼ਨ ਇਤਿਹਾਸ ਨਹੀਂ ਮਿਲਿਆ.",
      startNewConsultation: "ਨਵੀਂ ਕਨਸਲਟੇਸ਼ਨ ਸ਼ੁਰੂ ਕਰੋ",
      directory: "ਮਰੀਜ਼ ਡਾਇਰੈਕਟਰੀ",
      recentPatients: "ਹਾਲੀਆ ਮਰੀਜ਼",
      description: "ਹਾਲੀਆ ਮਰੀਜ਼ ਸੰਪਰਕ ਲੱਭੋ ਅਤੇ ਸਮੀਖਿਆ ਕਰੋ.",
      searchPlaceholder: "ਮਰੀਜ਼, ਟੈਗ ਲੱਭੋ...",
      noRecent: "ਕੋਈ ਹਾਲੀਆ ਮਰੀਜ਼ ਨਹੀਂ ਮਿਲਿਆ.",
      active: "ਸਰਗਰਮ",
      recent: "ਹਾਲੀਆ",
      generalConsult: "ਆਮ ਕਨਸਲਟ",
      ageGenderPending: "ਉਮਰ/ਲਿੰਗ ਬਾਕੀ",
      lastVisit: "ਆਖਰੀ ਵਿਜ਼ਿਟ",
      recently: "ਹਾਲ ਹੀ",
    },
    prescriptions: {
      detailsNotFound: "ਪ੍ਰਿਸਕ੍ਰਿਪਸ਼ਨ ਵੇਰਵੇ ਨਹੀਂ ਮਿਲੇ.",
      backToList: "ਸੂਚੀ ਵੱਲ ਵਾਪਸ",
      backToPrescriptions: "ਪ੍ਰਿਸਕ੍ਰਿਪਸ਼ਨ ਵੱਲ ਵਾਪਸ",
      prescription: "ਪ੍ਰਿਸਕ੍ਰਿਪਸ਼ਨ",
      issuedOn: "ਜਾਰੀ ਕੀਤਾ",
      copy: "ਕਾਪੀ",
      medications: "ਦਵਾਈਆਂ",
      instructions: "ਹਦਾਇਤਾਂ",
      manager: "ਪ੍ਰਿਸਕ੍ਰਿਪਸ਼ਨ ਮੈਨੇਜਰ",
      issuedPrescriptions: "ਜਾਰੀ ਪ੍ਰਿਸਕ੍ਰਿਪਸ਼ਨ",
      description: "ਪ੍ਰਿਸਕ੍ਰਿਪਸ਼ਨ ਇਤਿਹਾਸ ਲੱਭੋ, ਸਮੀਖਿਆ ਕਰੋ ਅਤੇ ਐਕਸਪੋਰਟ ਕਰੋ.",
      generateNew: "ਨਵਾਂ ਬਣਾਓ",
      searchPlaceholder: "ਮਰੀਜ਼, ਦਵਾ, ਨੋਟ ਲੱਭੋ...",
      noPrescriptions: "ਕੋਈ ਪ੍ਰਿਸਕ੍ਰਿਪਸ਼ਨ ਨਹੀਂ ਮਿਲੀ.",
      date: "ਮਿਤੀ",
    },
    availability: {
      fetchFailed: "ਸ਼ਡਿਊਲ ਲਿਆਉਣ ਵਿੱਚ ਅਸਫਲ",
      saved: "ਸ਼ਡਿਊਲ ਸਫਲਤਾਪੂਰਵਕ ਸੇਵ ਹੋਇਆ!",
      saveFailed: "ਸ਼ਡਿਊਲ ਸੇਵ ਨਹੀਂ ਹੋਇਆ.",
      networkError: "ਨੈੱਟਵਰਕ ਗਲਤੀ ਆਈ.",
      planner: "ਉਪਲਬਧਤਾ ਪਲੈਨਰ",
      weeklySchedule: "ਹਫ਼ਤਾਵਾਰੀ ਸ਼ਡਿਊਲ",
      description: "ਦੁਹਰਾਏ ਜਾਣ ਵਾਲੇ ਸਲਾਟ, ਬ੍ਰੇਕ ਸਮੇਂ ਅਤੇ ਆਨਲਾਈਨ ਤਿਆਰੀ ਸੈੱਟ ਕਰੋ.",
      saveChanges: "ਬਦਲਾਅ ਸੇਵ ਕਰੋ",
      activeDays: "ਸਰਗਰਮ ਦਿਨ",
      defaultStart: "ਡਿਫਾਲਟ ਸ਼ੁਰੂ",
      breakBuffer: "ਬ੍ਰੇਕ ਬਫਰ",
      availableForConsultations: "ਕਨਸਲਟੇਸ਼ਨਾਂ ਲਈ ਉਪਲਬਧ",
      unavailable: "ਉਪਲਬਧ ਨਹੀਂ",
      to: "ਤੋਂ",
      videoChat: "ਵੀਡੀਓ + ਚੈਟ",
      breaksAutoBuffered: "ਬ੍ਰੇਕ ਆਟੋ-ਬਫਰ",
      noBookings: "ਇਸ ਦਿਨ ਮਰੀਜ਼ ਬੁਕਿੰਗ ਨਹੀਂ.",
      days: ["ਸੋਮਵਾਰ", "ਮੰਗਲਵਾਰ", "ਬੁੱਧਵਾਰ", "ਵੀਰਵਾਰ", "ਸ਼ੁੱਕਰਵਾਰ", "ਸ਼ਨੀਵਾਰ", "ਐਤਵਾਰ"],
    },
    analytics: {
      loading: "ਐਨਾਲਿਟਿਕਸ ਲੋਡ ਹੋ ਰਹੀ ਹੈ...",
      failed: "ਐਨਾਲਿਟਿਕਸ ਲੋਡ ਨਹੀਂ ਹੋਈ.",
      intelligence: "ਪ੍ਰੈਕਟਿਸ ਇੰਟੈਲੀਜੈਂਸ",
      title: "ਐਨਾਲਿਟਿਕਸ",
      description: "ਪੂਰੀਆਂ ਕਨਸਲਟੇਸ਼ਨਾਂ, ਗਤੀ, ਵਾਧਾ ਅਤੇ ਮਰੀਜ਼ ਮਿਸ਼ਰਣ ਟ੍ਰੈਕ ਕਰੋ.",
      weeklyTrend: "+12% ਹਫ਼ਤਾਵਾਰੀ ਰੁਝਾਨ",
      totalPatients: "ਕੁੱਲ ਮਰੀਜ਼",
      lifetimeReach: "ਕੁੱਲ ਪਹੁੰਚ",
      completed: "ਪੂਰਾ",
      thisMonth: "ਇਸ ਮਹੀਨੇ",
      revenue: "ਆਮਦਨ",
      estimatedEarnings: "ਅਨੁਮਾਨਿਤ ਕਮਾਈ",
      satisfaction: "ਸੰਤੁਸ਼ਟੀ",
      patientRating: "ਮਰੀਜ਼ ਰੇਟਿੰਗ",
      consultationGrowth: "ਕਨਸਲਟੇਸ਼ਨ ਵਾਧਾ",
      weeklyAppointmentTrend: "ਹਫ਼ਤਾਵਾਰੀ ਅਪਾਇੰਟਮੈਂਟ ਰੁਝਾਨ",
      patientMix: "ਮਰੀਜ਼ ਮਿਸ਼ਰਣ",
      demographicDistribution: "ਡੈਮੋਗ੍ਰਾਫਿਕ ਵੰਡ",
      noData: "ਡਾਟਾ ਉਪਲਬਧ ਨਹੀਂ",
      patients: "ਮਰੀਜ਼",
    },
    profile: {
      updatePictureTitle: "ਪ੍ਰੋਫਾਈਲ ਤਸਵੀਰ ਅਪਡੇਟ ਕਰੋ",
      uploadingPhoto: "ਤਸਵੀਰ ਅਪਲੋਡ ਹੋ ਰਹੀ ਹੈ...",
      professionalProfile: "ਪੇਸ਼ੇਵਰ ਪ੍ਰੋਫਾਈਲ",
      description: "ਮਰੀਜ਼ਾਂ ਲਈ ਆਪਣੀ ਜਨਤਕ ਪ੍ਰੋਫਾਈਲ ਸਾਫ਼ ਅਤੇ ਭਰੋਸੇਯੋਗ ਰੱਖੋ.",
      commandCenter: "ਪ੍ਰੋਫਾਈਲ ਕਮਾਂਡ ਸੈਂਟਰ",
      title: "ਪੇਸ਼ੇਵਰ ਪ੍ਰੋਫਾਈਲ",
      summary: "ਵਿਸ਼ੇਸ਼ਤਾ, ਕਲੀਨਿਕ ਪਹਿਚਾਣ, ਸਰਟੀਫਿਕੇਸ਼ਨ, ਫੀਸ ਅਤੇ ਉਪਲਬਧਤਾ ਸਾਰ ਸੰਭਾਲੋ.",
      updateFailed: "ਪ੍ਰੋਫਾਈਲ ਅਪਡੇਟ ਨਹੀਂ ਹੋਈ.",
      updated: "ਪ੍ਰੋਫਾਈਲ ਸਫਲਤਾਪੂਰਵਕ ਅਪਡੇਟ ਹੋਈ!",
      pictureUpdateFailed: "ਪ੍ਰੋਫਾਈਲ ਤਸਵੀਰ ਅਪਡੇਟ ਨਹੀਂ ਹੋਈ.",
      pictureUpdated: "ਪ੍ਰੋਫਾਈਲ ਤਸਵੀਰ ਸਫਲਤਾਪੂਰਵਕ ਅਪਡੇਟ ਹੋਈ!",
      errorPrefix: "ਗਲਤੀ:",
      stats: {
        specialization: "ਵਿਸ਼ੇਸ਼ਤਾ",
        addSpecialty: "ਵਿਸ਼ੇਸ਼ਤਾ ਜੋੜੋ",
        experience: "ਤਜਰਬਾ",
        addYears: "ਸਾਲ ਜੋੜੋ",
        fee: "ਫੀਸ",
        addFee: "ਫੀਸ ਜੋੜੋ",
      },
      sections: {
        basicInformation: "ਮੂਲ ਜਾਣਕਾਰੀ",
        clinicDetails: "ਕਲੀਨਿਕ ਵੇਰਵੇ",
        professionalBio: "ਪੇਸ਼ੇਵਰ ਬਾਇਓ",
      },
      fields: {
        specialty: "ਵਿਸ਼ੇਸ਼ਤਾ",
        specialtyPlaceholder: "ਜਿਵੇਂ Cardiologist",
        qualification: "ਯੋਗਤਾ",
        qualificationPlaceholder: "ਜਿਵੇਂ MBBS, MD",
        experience: "ਤਜਰਬਾ",
        experiencePlaceholder: "ਜਿਵੇਂ 10 ਸਾਲ",
        fee: "ਕਨਸਲਟੇਸ਼ਨ ਫੀਸ",
        feePlaceholder: "ਜਿਵੇਂ 500",
        languages: "ਬੋਲੀਆਂ ਜਾਣ ਵਾਲੀਆਂ ਭਾਸ਼ਾਵਾਂ",
        languagesPlaceholder: "ਜਿਵੇਂ English, Hindi",
        clinicName: "ਕਲੀਨਿਕ ਨਾਮ",
        clinicNamePlaceholder: "ਤੁਹਾਡੇ ਕਲੀਨਿਕ ਦਾ ਨਾਮ",
        registrationNumber: "ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਨੰਬਰ",
        registrationPlaceholder: "ਮੈਡੀਕਲ ਕੌਂਸਲ ਰਜਿ. ਨੰ.",
        clinicAddress: "ਕਲੀਨਿਕ ਪਤਾ",
        clinicAddressPlaceholder: "ਤੁਹਾਡੇ ਕਲੀਨਿਕ ਦਾ ਪੂਰਾ ਪਤਾ...",
        bioPlaceholder: "ਮਰੀਜ਼ਾਂ ਨੂੰ ਆਪਣੇ ਤਜਰਬੇ ਅਤੇ ਚਿਕਿਤਸਕ ਸੋਚ ਬਾਰੇ ਦੱਸੋ...",
      },
      saving: "ਬਦਲਾਅ ਸੇਵ ਹੋ ਰਹੇ ਹਨ...",
      saveProfile: "ਪ੍ਰੋਫਾਈਲ ਸੇਵ ਕਰੋ",
    },
  },
};

export function getDoctorDashboardCopy(language = "en") {
  return doctorDashboardCopy[language] || doctorDashboardCopy.en;
}
